### ISSUE TITLE
block end message

### ISSUE THREAD

**Issue by SantiGarciaG** [SantiGarciaG/AA_expII#8]
Thanks a lot for resolving all of the issues, it seems to be working pretty well so far. 

I have failed to modified lines 162 & 163, perhaps you you could also help me with this...

I'm trying to change slightly when we show the end of block message, which in the recycled code we had it as < 4 (because we only had 5 blocks) and instead I'd like it to: 

1) appear after each block, except the last one of course, 
2) show it until the participant clicks.

**Comment by cherepaha** [comment]
Well, it's actually relatively tricky now to _not_ show the block-end screen in the final block. The tricky thing is that the appearance of this screen is currently controlled from within a block. Since we now don't have fixed number of blocks, each block doesn't know whether or not it is the last one, so it can't switch the message on or off... Would that be a problem if we just show the end of the block message at the end of each block? (including the last block) Theoretically, we can move the control of the end-block screen to the run_experiment() function, but this would be inconsistent with the overall logic throughout the code...

**Comment by cherepaha** [comment]
For now, I'm committing a version which shows the end-block screen unconditionally. If you feel this is important, I'll try to work on the issue further.

**Comment by SantiGarciaG** [comment]
No, it is not a big deal if we show that message at the end too. At least I'm please that that is exactly what I thought when I was thinking about that (but since what usually seems tricky to me is usually very easy to you I opted for mentioning it). 

What about showing the message until they click? (right now is timed and I can't find where do we specify this!)

**Comment by cherepaha** [comment]
For some reason it didn't work, but the screen was actually shown until mouse click. I think when the user clicks on the previous (rating) screen, the button remains pressed for some time, during which the screen is changed. I've fixed this by adding 100 ms delay before showing the block end screen (actually, before any message screen requiring click), seems to be working properly now.
